version: 2
jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - deploy:
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker build -t avvo/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 --build-arg PACKAGECLOUD_READ_TOKEN=$PACKAGECLOUD_READ_TOKEN .
            docker push avvo/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
